# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KudaGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  
    target 'KudaGoTests' do
      pod 'SnapshotTesting', '~> 1.9.0'
    end
end
